from .admin_views import *
from .auth_view import *
from .attendance_views import *
from .forms_views import *
from .mail_views import *
from .meeting_views import *
from .mentor_views import *
from .mentee_views import *
from .mmpairs_views import *
from .views import *