# Generated by Django 4.2.5 on 2023-11-26 16:55

from django.db import migrations, models


def create_initial_forms(apps, schema_editor):
    FormStatus = apps.get_model('server', 'FormStatus')

    FormStatus.objects.create(formId='1', formStatus='0')
    FormStatus.objects.create(formId='2', formStatus='0')
    FormStatus.objects.create(formId='3', formStatus='0')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('email', models.CharField()),
                ('name', models.CharField()),
                ('department', models.CharField()),
                ('phone', models.CharField()),
                ('address', models.CharField()),
                ('imgSrc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendeeId', models.CharField()),
                ('meetingId', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('email', models.CharField()),
                ('name', models.CharField()),
                ('department', models.CharField()),
                ('year', models.CharField()),
                ('status', models.IntegerField()),
                ('contact', models.CharField()),
                ('size', models.CharField()),
                ('score', models.CharField()),
                ('imgSrc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormResponses',
            fields=[
                ('SubmissionId', models.AutoField(primary_key=True, serialize=False)),
                ('submitterId', models.CharField()),
                ('FormType', models.CharField()),
                ('responses', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormStatus',
            fields=[
                ('formId', models.CharField(primary_key=True, serialize=False)),
                ('formStatus', models.CharField()),
            ],
        ),
        migrations.RunPython(create_initial_forms),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('meetingId', models.AutoField(primary_key=True, serialize=False)),
                ('schedulerId', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('attendee', models.IntegerField()),
                ('mentorBranches', models.JSONField(default=list)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('email', models.CharField()),
                ('name', models.CharField()),
                ('department', models.CharField()),
                ('contact', models.CharField()),
                ('imgSrc', models.TextField()),
                ('mentorId', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('goodiesStatus', models.IntegerField()),
            ],
        ),
    ]
