# Generated by Django 4.2.5 on 2023-11-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('email', models.CharField()),
                ('name', models.CharField()),
                ('department', models.CharField()),
                ('phone', models.CharField()),
                ('address', models.CharField()),
                ('imgSrc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendee_id', models.CharField(primary_key=True, serialize=False)),
                ('meeting', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('email', models.CharField()),
                ('name', models.CharField()),
                ('department', models.CharField()),
                ('year', models.CharField()),
                ('size', models.CharField()),
                ('score', models.CharField()),
                ('imgSrc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormResponses',
            fields=[
                ('form_id', models.CharField(primary_key=True, serialize=False)),
                ('submitter_id', models.CharField()),
                ('responses', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('meeting_id', models.CharField(primary_key=True, serialize=False)),
                ('scheduler_id', models.CharField()),
                ('date', models.CharField()),
                ('time', models.CharField()),
                ('attendee', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('email', models.CharField()),
                ('name', models.CharField()),
                ('department', models.CharField()),
                ('imgSrc', models.TextField()),
                ('mentor_id', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('goodiesStatus', models.CharField()),
                ('reimbursement', models.CharField()),
            ],
        ),
    ]
