# Generated by Django 5.2.5 on 2025-08-22 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(choices=[('mentor_mapping', 'Mentor-Mentee Mapping'), ('consent', 'Consent Form'), ('general', 'General Email')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('department', models.CharField(max_length=10)),
                ('recipient_emails', models.JSONField()),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_schedule',
            },
        ),
        migrations.AddField(
            model_name='mentee',
            name='first_login_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('email_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.emailschedule')),
            ],
            options={
                'db_table': 'email_log',
            },
        ),
    ]
