# Generated by Django 4.2.5 on 2024-02-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='menteeBranches',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='meetings',
            name='menteeList',
            field=models.JSONField(default=list),
        ),
    ]
