# Generated by Django 5.2.5 on 2025-08-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_emailschedule_mentee_first_login_completed_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academic_year',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(default='Even', max_length=20)),
                ('user_type', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('imgSrc', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('mentorId', models.CharField(blank=True, max_length=50, null=True)),
                ('first_login_completed', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'historical_data',
                'indexes': [models.Index(fields=['academic_year', 'user_type'], name='historical__academi_1fc5de_idx'), models.Index(fields=['user_type', 'department'], name='historical__user_ty_9eed75_idx')],
            },
        ),
    ]
