# Generated by Django 4.2.5 on 2024-02-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_meetings_menteebranches_meetings_menteelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
