# Generated by Django 4.2.5 on 2023-11-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_candidate_status_meetings_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendee_id',
            new_name='attendeeId',
        ),
        migrations.RenameField(
            model_name='formresponses',
            old_name='form_id',
            new_name='formId',
        ),
        migrations.RenameField(
            model_name='formresponses',
            old_name='submitter_id',
            new_name='submitterId',
        ),
        migrations.RenameField(
            model_name='meetings',
            old_name='meeting_id',
            new_name='meetingId',
        ),
        migrations.RenameField(
            model_name='meetings',
            old_name='scheduler_id',
            new_name='schedulerId',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='mentor_id',
            new_name='mentorId',
        ),
    ]
