# Generated by Django 4.2.5 on 2024-03-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_delete_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcellenceAward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidateId', models.CharField()),
            ],
        ),
    ]
