# Generated by Django 4.2.5 on 2023-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_attendee_id_attendance_attendeeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
